export const items = [
  {
    title: "Grilled chicken pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/pizza recipe 1.avif",
    category: "pizza",
    id: 1,
  },
  {
    title: "Cheese pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "90",
    src: "/images/pizza recipe 2.avif",
    category: "pizza",
    id: 2,
  },
  {
    title: "Veggie pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "20",
    src: "/images/pizza recipe 3.avif",
    category: "pizza",
    id: 3,
  },
  {
    title: "Pepperoni pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "30",
    src: "/images/pizza recipe 4.avif",
    category: "pizza",
    id: 4,
  },
  {
    title: "Meat pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/pizza recipe 5.avif",
    category: "pizza",
    id: 5,
  },
  {
    title: "Hawaiian pizza",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/pizza recipe 6.avif",
    category: "pizza",
    id: 6,
  },

  {
    title: "Bison Burger",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/burger 1.avif",
    category: "snacks",
    id: 7,
  },
  {
    title: "Turkey Burger",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/burger 2.avif",
    category: "snacks",
    id: 8,
  },
  {
    title: "Beef Burger",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/burger 3.avif",
    category: "snacks",
    id: 9,
  },
  {
    title: "Beef Sharwama",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/sharwama 1.avif",
    category: "snacks",
    id: 10,
  },
  {
    title: "Chicken Sharwama",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/sharwama 2.avif",
    category: "snacks",
    id: 11,
  },
  {
    title: "Meat Pie",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "50",
    src: "/images/meatpie 2.avif",
    category: "snacks",
    id: 12,
  },
  {
    title: "Yummy Lasagna",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "90",
    src: "/images/lasgna 3.avif",
    category: "snacks",
    id: 13,
  },
  {
    title: "Lasagna",
    description: "lorem1jjjjjjjjjjjjjjjjjjjjjj",
    price: "30",
    src: "/images/lasagna 4.avif",
    category: "snacks",
    id: 14,
  },
];
