import Nav from "../../components/Nav/Nav";
import Head from "next/head";
import Tabs from "/components/Tabs/Tabs.js";
import Footer from "../../components/Footer/Footer";
import Loader from "/components/Loaders/MenuLoader.js";

import { useState, useEffect } from "react";
// import { useRouter } from "next/router";
import styles from "../../styles/pages/Menu.module.scss";

import Card from "../../components/Card/Card.js";
import { items } from "../../db/items";
import Link from "next/link";

export default function Menu() {
  const [tabIndex, setTabIndex] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 3500);
  });

  if (loading) {
    return <Loader />;
  }

  // const router = useRouter();
  // console.log(router);

  const pizza = items.filter((item) => item.category === "pizza");
  const snacks = items.filter((item) => item.category === "snacks");

  return (
    <div className={styles.container}>
      <Head>
        <title>YummyPiz Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.jpg" />
      </Head>

      <Nav position={"absolute"} />
      <main>
        <Tabs tabIndex={tabIndex} setTabIndex={setTabIndex} />
        <div className={styles.cards}>
          {tabIndex === 0 &&
            items.map((item) => (
              <Link key={item.id} href={"/menu/" + item.id}>
                <Card item={item} />
              </Link>
            ))}

          {tabIndex === 1 &&
            pizza.map((item) => (
              <Link key={item.id} href={"/menu/" + item.id}>
                <Card item={item} />
              </Link>
            ))}

          {tabIndex === 2 &&
            snacks.map((item) => (
              <Link key={item.id} href={"/menu/" + item.id}>
                <Card item={item} />
              </Link>
            ))}
        </div>
      </main>
      <Footer position="static" />
    </div>
  );
}
