import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/Home.module.scss";
import Loader from "/components/Loaders/HomeLoader.js";
import Nav from "../components/Nav/Nav";
import Footer from "../components/Footer/Footer";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 6000);
  });

  if (loading) {
    return <Loader />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>YummyPiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.jpg" />
      </Head>
      <Nav position={"absolute"} />

      <main className={styles.main}>
        <div className={styles.heroImg}></div>
        <div className={styles.heroContent}>
          <h1>Hello world</h1>
          <span>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia
            perspiciatis reiciendis aliquam magni laudantium deleniti explicabo
            iusto, dolorum vero hic beatae error perferendis alias at atque
            libero animi culpa voluptatum?
          </span>
          <Link href="/menu">
            <button>Make Orders now</button>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
